version: '3.0'

services:
  consulserver:
    image: progrium/consul:latest
    hostname: consulserver
    container_name: consulserver
    restart: always
    environment:
      SERVICE_TAGS: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302/udp"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: -server -ui-dir /ui -data-dir /tmp/consul --bootstrap-expect=2 -client 0.0.0.0

  consulserver1:
    image: progrium/consul:latest
    hostname: consulserver1
    container_name: consulserver1
    environment:
      SERVICE_TAGS: consul
    restart: always
    depends_on:
      - consulserver
    ports:
      - "19300:8300"
      - "19301:8301"
      - "19301:8301/udp"
      - "19302:8302/udp"
      - "19302:8302"
      - "19400:8400"
      - "19500:8500"
      - "19600:8600"
    command: -server -data-dir /tmp/consul -join consulserver -client 0.0.0.0

  consulserver2:
    image: progrium/consul:latest
    hostname: consulserver2
    container_name: consulserver2
    environment:
      SERVICE_TAGS: consul
    restart: always
    depends_on:
      - consulserver
    ports:
      - "17300:8300"
      - "17301:8301"
      - "17301:8301/udp"
      - "17302:8302/udp"
      - "17302:8302"
      - "17400:8400"
      - "17500:8500"
      - "17600:8600"
    command: -server -data-dir /tmp/consul -join consulserver -client 0.0.0.0

  consulserver3:
    image: progrium/consul:latest
    hostname: consulserver3
    container_name: consulserver3
    environment:
      SERVICE_TAGS: consul
    restart: always
    depends_on:
      - consulserver
    ports:
      - "10300:8300"
      - "10301:8301"
      - "10301:8301/udp"
      - "10302:8302/udp"
      - "10302:8302"
      - "10400:8400"
      - "10500:8500"
      - "10600:8600"
    command: -ui-dir /ui -data-dir /tmp/consul -retry-join consulserver -client 0.0.0.0


  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator
    container_name: registrator
    restart: always
    depends_on:
      - consulserver
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consulserver:8500
