version: '3'
services:
  mysql:
    image: jumpserver/jms_mysql:${JumpServerVersion}
    container_name: jms_mysql
    restart: always
    tty: true
    env_file:
      - ./.envs/.jumpserver/.mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jumpserver

  redis:
    image: jumpserver/jms_redis:${JumpServerVersion}
    container_name: jms_redis
    restart: always
    tty: true
    env_file:
      - ./.envs/.jumpserver/.redis
    volumes:
      - redis-data:/var/lib/redis/
    networks:
      - jumpserver

  core:
    image: jumpserver/jms_core:${JumpServerVersion}
    container_name: jms_core
    restart: always
    tty: true
    env_file:
      - ./.envs/.jumpserver/.mysql
      - ./.envs/.jumpserver/.redis
      - ./.envs/.jumpserver/.core
    depends_on:
      - mysql
      - redis
    volumes:
      - core-data:/opt/jumpserver/data
    networks:
      - jumpserver

  koko:
    image: jumpserver/jms_koko:${JumpServerVersion}
    container_name: jms_koko
    restart: always
    privileged: true
    tty: true
    env_file:
      - ./.envs/.jumpserver/.koko
      - ./.envs/.jumpserver/.core
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - koko-data:/opt/koko/data
    ports:
      - 2222:2222
    networks:
      - jumpserver

  guacamole:
    image: jumpserver/jms_guacamole:${JumpServerVersion}
    container_name: jms_guacamole
    restart: always
    tty: true
    env_file:
      - ./.envs/.jumpserver/.guacamole
      - ./.envs/.jumpserver/.core
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - guacamole-data:/config/guacamole/data
    networks:
      - jumpserver

  nginx:
    image: jumpserver/jms_nginx:${JumpServerVersion}
    container_name: jms_nginx
    restart: always
    tty: true
    depends_on:
      - core
      - koko
      - mysql
      - redis
    volumes:
      - core-data:/opt/jumpserver/data
    ports:
      - 80:80
    networks:
      - jumpserver

volumes:
  mysql-data:
  redis-data:
  core-data:
  koko-data:
  guacamole-data:

networks:
  jumpserver:
