# https://www.mkdocs.org/
site_name: super-miner
site_description:
repo_url: https://github.com/bingryan/super-miner
site_dir: super-miner
copyright:
dev_addr: 0.0.0.0:8002
theme:
  name: 'material'
  font:
    text: Ubuntu
    code: Ubuntu Mono


nav:
    - 文档概要: 'README.md'
    - 常用脚本: 'script/README.md'
        - docker: 'script/docker.md'
    - 项目实施文档: 'documents/index.md'
    - 母盘制作: 'startup.md'
    - ansible运维: 'ansible/README.md'
        - 批量处理: 'ansible/batch.md'
    - 监控dashboard: 'startup.md'
    - 预警: 'alert.md'
    - 硬盘操作: 'disk'
    - 堡垒机JumpServer: 'jumpserver/README.md'
    - 日志处理: 'logs.md'



markdown_extensions:
  - meta
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
