# https://www.mkdocs.org/
site_name: super-miner
site_description: 家用挖矿、自建机房、IDC机房等场景的一个可组合挖矿机器管理方案
repo_name: 'bingryan/super-miner'
repo_url: https://github.com/bingryan/super-miner
site_dir: super-miner
copyright:
dev_addr: 0.0.0.0:8002
theme:
  name: 'material'
  font:
    text: Ubuntu
    code: Ubuntu Mono


nav:
    - 文档概要: 'README.md'
    - 脚本:
       - 常用脚本: 'script/README.md'
       - docker: 'script/docker.md'
       - python: 'script/python.md'
    - 项目实施文档: 'deploy.md'
    - 母盘制作: 'startup.md'
    - ansible:
        - 运维: 'ansible/README.md'
        - 批量处理: 'ansible/batch.md'
    - 监控dashboard: 'dashboard/README.md'
    - 预警: 'alert.md'
    - 硬盘操作: 'disk.md'
    - 资源限制: 'limit.md'
    - 堡垒机JumpServer: 'jumpserver/README.md'
    - 日志处理: 'logs.md'



markdown_extensions:
  - meta
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
